# Generated by Django 4.2.6 on 2023-10-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=100)),
                ('car_year', models.IntegerField()),
                ('car_color', models.CharField(max_length=100)),
                ('car_mileage', models.IntegerField()),
                ('car_price', models.IntegerField()),
            ],
        ),
    ]
